services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: crud_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4144  # Coincide con la contraseña en DATABASE_URL
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: